require: rubocop-rails

AllCops:
  NewCops: enable

  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'config/*'
    - 'test/**/*'
    - 'db/**/*'

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30